### ISSUE TITLE
Project is missing the 'contracts' folder in frontend/src

### ISSUE THREAD

**Issue by jefflam** [remote-gildor/hardhat-vue-starter#2]
Was looking for a hardhat and vue starter kit, so thanks!

Ran into an error as I was deploying the contracts -- you're missing a `contracts` folder in `frontend/src` directory. This causes `fs.copyFileSync` to fail as it is unable to find the `contracts` directory and thus it is unable to create and paste the `addresses.json` file in that directory.

Just a small fix!

**Comment by remote-gildor** [comment]
You're right, I don't know why I had this in gitignore. It's removed now. Thanks!
